define({
    None: -1,
    Unknown: 0,
    YouTubePlaylist: 1,
    YouTubeChannel: 2,
    SharedPlaylist: 3,
    UserInput: 4,
    YouTubeFavorites: 5,
    YouTubeAutoGenerated: 6,
    YouTubeVideo: 7
});