define([
    'youTubeDataApi'
], function (YouTubeDataAPI) {
    'use strict';

    console.log('YouTube API:', YouTubeDataAPI);
    
    describe('YouTubeDataAPI', function () {

        it('Should be able to get auto-generated playlist data', function () {

            var autoGeneratedPlaylistData = null;
            runs(function() {
                YouTubeDataAPI.getAutoGeneratedPlaylistData('ALYL4kY05133rTMhTulSaXKj_Y6el9q0JH', function (response) {
                    autoGeneratedPlaylistData = response.results;
                });
            }, 500);

            waitsFor(function() {
                return autoGeneratedPlaylistData !== null;
            }, "The autoGeneratedPlaylistData should be set ", 1000);

            runs(function () {
                expect(autoGeneratedPlaylistData.length).toBeGreaterThan(0);
                expect(autoGeneratedPlaylistData.length).toBeLessThan(51);
            });
            
        });

        it('Should be able to get an auto-generated playlist\'s name', function() {

            var autoGeneratedPlaylistTitle = null;
            runs(function () {
                YouTubeDataAPI.getAutoGeneratedPlaylistTitle('ALYL4kY05133rTMhTulSaXKj_Y6el9q0JH', function (response) {
                    autoGeneratedPlaylistTitle = response;
                });
            }, 500);

            waitsFor(function () {
                return autoGeneratedPlaylistTitle !== null;
            }, "The autoGeneratedPlaylistTitle should be set ", 1000);

            runs(function () {
                expect(autoGeneratedPlaylistTitle).not.toEqual('');
                expect(autoGeneratedPlaylistTitle).toEqual('Top Tracks for Kendrick Lamar');
            });

        });

        xit('Should be able to login to YouTube', function () {
            YouTubeDataAPI.doYouTubeLogin();
        });

    });
    
});

