define([
    'youTubeDataApi'
], function (YouTubeDataAPI) {
    'use strict';
    
    describe('YouTubeDataAPI', function () {

        it('Should be able to get auto-generated playlist data', function () {

            var autoGeneratedPlaylistData = null;
            runs(function() {
                YouTubeDataAPI.getAutoGeneratedPlaylistData('ALYL4kY05133rTMhTulSaXKj_Y6el9q0JH', function (response) {
                    autoGeneratedPlaylistData = response;
                });
            }, 500);

            waitsFor(function() {
                return autoGeneratedPlaylistData !== null;
            }, "The autoGeneratedPlaylistData should be set ", 750);

            runs(function () {
                expect(autoGeneratedPlaylistData.length).toBeGreaterThan(0);
                expect(autoGeneratedPlaylistData.length).toBeLessThan(51);
            });
            
        });

        xit('Should be able to login to YouTube', function () {
            YouTubeDataAPI.doYouTubeLogin();
        });

    });
    
});

