define([
    'test/foreground/view/prompt/browserSettingsPromptViewTest',
    'test/foreground/view/prompt/browserSettingsViewTest',
    'test/foreground/view/prompt/clearStreamPromptViewTest',
    'test/foreground/view/prompt/createPlaylistPromptViewTest',
    'test/foreground/view/prompt/createPlaylistViewTest',
    'test/foreground/view/prompt/deletePlaylistPromptViewTest',
    'test/foreground/view/prompt/deletePlaylistViewTest',
    'test/foreground/view/prompt/editPlaylistPromptViewTest',
    'test/foreground/view/prompt/editPlaylistViewTest',
    'test/foreground/view/prompt/errorPromptViewTest',
    'test/foreground/view/prompt/exportPlaylistPromptViewTest',
    'test/foreground/view/prompt/exportPlaylistViewTest',
    'test/foreground/view/prompt/googleSignInPromptViewTest',
    'test/foreground/view/prompt/linkUserIdPromptViewTest',
    'test/foreground/view/prompt/promptRegionTest',
    'test/foreground/view/prompt/promptViewTest',
    'test/foreground/view/prompt/saveSongsPromptViewTest',
    'test/foreground/view/prompt/saveSongsViewTest',
    'test/foreground/view/prompt/settingsPromptViewTest',
    'test/foreground/view/prompt/settingsViewTest',
    'test/foreground/view/prompt/updateStreamusPromptViewTest'
], function () {
});