define([
    'test/foreground/view/dialog/browserSettingsDialogViewTest',
    'test/foreground/view/dialog/browserSettingsViewTest',
    'test/foreground/view/dialog/clearStreamDialogViewTest',
    'test/foreground/view/dialog/createPlaylistDialogViewTest',
    'test/foreground/view/dialog/createPlaylistViewTest',
    'test/foreground/view/dialog/deletePlaylistDialogViewTest',
    'test/foreground/view/dialog/deletePlaylistViewTest',
    'test/foreground/view/dialog/editPlaylistDialogViewTest',
    'test/foreground/view/dialog/editPlaylistViewTest',
    'test/foreground/view/dialog/errorDialogViewTest',
    'test/foreground/view/dialog/exportPlaylistDialogViewTest',
    'test/foreground/view/dialog/exportPlaylistViewTest',
    'test/foreground/view/dialog/googleSignInDialogViewTest',
    'test/foreground/view/dialog/linkUserIdDialogViewTest',
    'test/foreground/view/dialog/dialogRegionTest',
    'test/foreground/view/dialog/dialogViewTest',
    'test/foreground/view/dialog/settingsDialogViewTest',
    'test/foreground/view/dialog/settingsViewTest',
    'test/foreground/view/dialog/updateStreamusDialogViewTest'
], function () {
});