define([
    'jquery'
], function ($) {
    'use strict';

    var dataSourceEnum = {
        YOUTUBE_PLAYLIST: 0,
        YOUTUBE_CHANNEL: 1,
        SHARED_PLAYLIST: 2,
        USER_INPUT: 3,
        YOUTUBE_FAVORITES: 4,
        YOUTUBE_AUTOGENERATED: 5,
    };

    return $.extend({}, dataSourceEnum, {

        //  These data sources require using YouTube V3 API to retrieve their information.
        isV3: function (dataSource) {
            return dataSource === dataSourceEnum.YOUTUBE_AUTOGENERATED;
        },
        
        //  These data sources require going out to a server and collecting a list of information in order to be created.
        needsLoading: function(dataSource) {
            return dataSource === dataSourceEnum.YOUTUBE_CHANNEL ||
                dataSource === dataSourceEnum.YOUTUBE_PLAYLIST ||
                dataSource === dataSourceEnum.YOUTUBE_FAVORITES ||
                dataSource === dataSourceEnum.YOUTUBE_AUTOGENERATED;
        }      
    });
});